name: Test Formulae for SnapX
on:
  pull_request:
    types: [opened, synchronize]
    paths: ["Formula/snapx.rb"]
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  brew-test-bot:
    name: Brew Test Bot
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
        - name: Set environment variables
          id: set-env
          run: |
            export HOMEBREW_NO_INSTALL_FROM_API=1
            export HOMEBREW_NO_ENV_HINTS=1
        - name: Set up Homebrew
          id: set-up-homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Install required dependencies (on Ubuntu)
          id: install-deps-ubuntu
          if: runner.os == 'Linux'
          run: |
            sudo apt install -y xdg-utils

        - name: Brew Test Bot
          id: brew-test-bot
          run: |
            brew test-bot snapx
